[package]
name = "askalono"
version = "0.1.1"
description = "a library to detect the contents of license files"
license = "Apache-2.0"
repository = "https://github.com/amzn/askalono"
authors = ["Jacob Peddicord <peddicor@amazon.com>"]
readme = "README.md"
exclude = [
    "/license-list-data/**/*"
]

[dependencies]
flate2 = "1.0.1"
lazy_static = "0.2.9"
log = "0.3"
rayon = "0.8.2"
regex = "0.2.1"
rmp-serde = "0.13.6"
serde = "1.0.11"
serde_derive = "1.0.11"
unicode-normalization = "0.1.5"

# spdx deps
serde_json = { version = "1.0", optional = true }
walkdir = { version = "1.0.7", optional = true }

[workspace]
members = ["cli"]

[lib]
name = "askalono"
path = "src/lib.rs"

[features]
default = ["spdx"]
spdx = ["serde_json", "walkdir"]